apps:
  launcher-ot-minecraft:
    command: minecraft-launcher
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $JAVA_HOME/jre/bin:$PATH
    extensions:
    - gnome-3-38
    plugs:
    - gsettings
    - home
    - network
    - browser-support
    - audio-playback
    - opengl
    - x11
    - wayland
architectures:
  - build-on: amd64
base: core20
confinement: strict
description: "Other tarball launcher for Minecraft: Java Edition installable via Snap. Implemented using the core20 base and gnome-3-34 extension.\n*Not official Minecraft product. Not approved by or associated with Mojang.*"
icon: snap/gui/launcher-ot-minecraft.png
name: launcher-ot-minecraft
parts:
  minecraft-launcher:
    build-packages:
    - ca-certificates
    - ca-certificates-java
    plugin: dump
    source: https://launcher.mojang.com/download/Minecraft.tar.gz
    stage-packages:
    - default-jre
    - libxss1
    - libcurl4
summary: Other tarball launcher for Minecraft
title: Launcher for Minecraft
version: "1035"
