# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 08 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: version update
      run: |
        ls -a ~/
        sudo apt-get update && sudo apt-get install -y python3-setuptools
        python3 -m pip install PyYaml
        cd /tmp && wget https://launcher.mojang.com/download/Minecraft.tar.gz
        tar xfvz /tmp/Minecraft.tar.gz
        VERSION=$(python3 ~/minecraft-launcher-ot/.github/workflows/version.py /tmp/minecraft-launcher/minecraft-launcher)
        echo $VERSION
