# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 08 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: version update
      run: |
        sudo apt-get update && sudo apt-get install -y python3-setuptools
        python3 -m pip install PyYaml
        cd /tmp && wget https://launcher.mojang.com/download/Minecraft.tar.gz
        tar xfvz /tmp/Minecraft.tar.gz
        cd /home/runner/work/launcher-ot-minecraft/launcher-ot-minecraft
        VERSION=$(python3 .github/workflows/version.py /tmp/launcher-minecraft/launcher-minecraft)
        if [ $VERSION != "no commit needed" ]
        then 
          git config --global user.email "pabuffon@gmail.com"
          git config --global user.name "Pete Buffon"
          git tag $VERSION
          git commit -am "version update"
          git push origin --tags
        fi
    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: stable
